### PR TITLE
Fix: className() change to class

### PR DESCRIPTION
**Pull request by Felli**
This deals with a lot of fixes to the `className()` issues, also changes one array in Events.php to short array but that's a minor issue.

> Note: In `/widgets/AccountField.php` on [line 172](https://github.com/Coinsence/humhub-modules-xcoin/blob/master/widgets/AccountField.php#L172) I'm not exactly sure if this should or shouldn't be replaced with class or not, any advice would be appreciated! :smile:

### CODE REVIEW

**Comment by craxrev** [comment]
Yeah, seems nice if we consider preparing for the yii 2.1 version, though we should get rid of all depracated methods, found some unchanged `::className()` methods, so consider changing all occurences :smile: 
 
And oh about the note, you could consider changing it with the PHP `get_class($object)` method in favor of the deprecated one.

Otherwise lgtm :+1:

**Comment by craxrev** [comment]
@gdalyy what do you think?

**Comment by gdalyy** [comment]
Yes i think we should merge this PR , and as you said we should consider changing all occurences.
We should you static::class which is roughly 1/3rd faster than get_class.

lgtm :+1:

**Comment by Felli** [comment]
Sorry don't have much time to do many complete fixes at this time, I have marked it so that maintainers can do whatever edits they wish.

**Comment by Felli** [comment]
Is this pull still needed or should it be closed?

**Comment by gdalyy** [comment]
I'm closing this PR , we're dealing with `className()` issues in other separate PRs. Thanks

**Pull request closed without merging**
