### PR TITLE
Tup#26

### PR DESCRIPTION
**Pull request by gdalyy**
Enabling accounts creation for tasks

### CODE REVIEW

**Comment by gdalyy** [comment]
@bumi , @craxrev , we should merge this also because it's related to *task module* PR for tup#26 that has been recently merged.

**Comment by bumi** [comment]
ohh... I must have missed that one. 
but I guess this should go in master, no?

**Comment by gdalyy** [comment]
Yes i think so .

**Comment by bumi** [comment]
ok, can you make one for master?

**Comment by craxrev** [comment]
As the previous **task module** PR is commited into the tup#7 branch, this also should into the same branch.
When tup#7 branch in **task module** gets merged into master, then i think this also should be aswell, but before depoying in production, all tup#7 branches should be merged into their master.

**Comment by gdalyy** [comment]
@craxrev ,That's what i did, for the first time i was making a PR directly to master, and then i've introduced the tup#7 branch and i've changed the base branch of the PR .
@bumi , do you think that we must do the same thing as **task module** : tup#26 -> tup#7 then -> master ?

**Comment by bumi** [comment]
I am confused. 

actually I think ideally PRs are always into master. (and from master we deploy to dev/production) 
if I see this correctly then the tup7 branch is even with master? 

in the end this code has to go into master somehow :)

**Comment by gdalyy** [comment]
@bumi, since tup#7 contains multiple sub-issues, for the first time i thought that we should handle different sub-issues separately in different branches then merge all sub-issues branches (without PRs) into tup#7 then making a PR from tup#7 to master. But what we're doing right now, we're making PRs also between sub-issues and main parent issue, is this wrong ? 

What i think is we should make PRs only when merging with master and not also between different other branches. What do you think guys ?

**Comment by bumi** [comment]
no nothing wrong... can be done however you like it best. 

I think it is best to divide topics in small parts that can easily be reviewed and independently deployed. Thus a sub-task should still be a PR into master and from there deployed. 

PRs are always there for reviews and collaboration around some code changes this I think everything should be a PR. 

related: https://guides.github.com/introduction/flow/

**Comment by gdalyy** [comment]
Okay thanks @bumi , should we make a PR from tup#7 into master in both modules *task* & *x-coin* ?

**Comment by bumi** [comment]
oh damn, I thought in the task module everything is already in master. 
so yes, I'd see we need to get everything in master and deploy those features.

**Comment by gdalyy** [comment]
can you merge this first into tup#7 , then we make new PRs from tup#7 to master ?

**Pull request merged**
